import { StyleSheet } from 'react-native';

import { colors } from '../../../../styles/colors';

export default StyleSheet.create({
  container: {
    backgroundColor: colors.white,
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  backText: {
    color: colors.midGrey,
    fontSize: 16,
    fontWeight: '400',
    marginLeft: 7,
  },
  backButton: {
    marginTop: 100,
    marginBottom: 40,
    marginRight: 280,
  },
  passwordText: {
    marginRight: 253,
    fontSize: 13,
    opacity: 0.35,
  },
  instructionText: {
    color: colors.black,
    fontSize: 24,
    fontWeight: '800',
    marginRight: 70,
    marginBottom: 20,
  },
  displayTextStreet: {
    marginRight: 223,
    fontSize: 13,
    opacity: 0.35,
  },
  displayTextCity: {
    marginRight: 285,
    fontSize: 13,
    opacity: 0.35,
  },
  displayTextState: {
    marginRight: 80,
    fontSize: 13,
    opacity: 0.35,
  },
  displayTextZip: {
    marginLeft: 20,
    fontSize: 13,
    opacity: 0.35,
  },
  input: {
    marginBottom: 10,
    height: 40,
    borderBottomWidth: 0.75,
    width: 310,
    borderColor: colors.darkGrey,
  },
  inputFocused: {
    marginBottom: 10,
    height: 40,
    borderBottomWidth: 2,
    width: 310,
    borderColor: colors.darkRed,
    borderRadius: 2,
  },
  inputWrap: {
    flexDirection: 'row',
  },
  inputLeft: {
    marginBottom: 10,
    height: 40,
    borderBottomWidth: 0.75,
    width: 146,
    marginRight: 10,
    borderColor: colors.darkGrey,
  },
  inputLeftFocused: {
    marginBottom: 10,
    height: 40,
    borderBottomWidth: 2,
    width: 146,
    marginRight: 10,
    borderColor: colors.darkRed,
  },
  inputRight: {
    marginBottom: 10,
    height: 40,
    borderBottomWidth: 0.75,
    width: 146,
    borderColor: colors.darkGrey,
  },
  inputRightFocused: {
    marginBottom: 10,
    height: 40,
    borderBottomWidth: 2,
    width: 146,
    borderColor: colors.darkRed,
  },
  nextText: {
    color: colors.white,
    marginRight: 30,
    marginTop: 2,
    fontSize: 14,
    opacity: 1,
    fontWeight: '600',
  },
  nextButton: {
    backgroundColor: colors.black,
    marginBottom: 20,
    marginRight: 155,
    borderRadius: 3,
    borderColor: colors.black,
    width: 144,
    height: 50,
    padding: 15,
    marginTop: 50,
  },
  errorMessage: {
    color: colors.darkRed,
    fontSize: 14,
    fontWeight: '400',
    width: '81%',
    marginTop: 20,
    marginRight: 25,
    marginBottom: 20,
  },
});
